[package]
name = "family_banking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }
rust-argon2 = "1.0"